### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by cicero66** [dulaccc/DPMeterView#3]
Hello and thanks for making this available,

However after following the installation guide I still get this error:

ld: can't map file, errno=22 file 'Pods' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you help please ?

Thanks
Alex

**Comment by dulaccc** [comment]
Did you finally found out the reason of the compilation crash ?

**Comment by mzekrallah** [comment]
this is not compiling .. please check pod files .. thanks

**Comment by kartboy16** [comment]
The example project is missing $(inherited) under "Other Linker Flags"

Once you add $(inherited), run pod install and it should compile afterwards.

**Comment by dulaccc** [comment]
Indeed, with the `$(inherited)` flag it's working ! thanks for the tip @kartboy16
