### ISSUE TITLE
PocketSVG for using custom images as masks

### ISSUE THREAD

**Issue by comyarzaheri** [dulaccc/DPMeterView#4]
I'm using DPMeterView in one of my current projects and used PocketSVG (https://github.com/arielelkin/PocketSVG) to convert SVG images to CGPathRefs. I've had pretty good results with it, just a heads up.

**Comment by perry-mitchell** [comment]
I'm building an app using DPMeterView as well, but I opted for [UIBezierPath-SVG](https://github.com/ap4y/UIBezierPath-SVG) to convert SVG to CGPaths.

Fantastic library :)

**Comment by dulaccc** [comment]
I close this issue, because it wasn't even an issue actually :)

Cheers
