### ISSUE TITLE
Incorrect axis for gravity in landscape

### ISSUE THREAD

**Issue by perry-mitchell** [dulaccc/DPMeterView#5]
I'm using DPMeterView in a UIViewController that has rotation enabled. In portrait, the gravity for the gauge works flawlessly, though when the view controller rotates to landscape, the gauge doesn't operate on the 'same' axis (it instead only responds to being tilted forward and back - pitch instead of yaw).

Here is a snippet of code I'm using:

```
	brainMeter = [[DPMeterView alloc] init];
	[brainMeter setFrame:CGRectMake(0, 0, screenSize.width - (IMAGE_INSET * 2), screenSize.width - (IMAGE_INSET * 2))];
	[brainMeter setMeterType:DPMeterTypeLinearVertical];
	[brainMeter setProgressTintColor:[UIColor redColor]];
	[brainMeter setTrackTintColor:[UIColor colorWithWhite:0.79 alpha:1.0]];

	// path stuff from SVG

	[self addSubview:brainMeter];
	[brainMeter setProgress:0.5 animated:NO];
	[brainMeter startGravity];
```

Any ideas? I'm not doing anything tricky with the device rotation, it's all standard stuff.

**Comment by dulaccc** [comment]
Indeed, there is no support for rotation yet. So, it's reassuring me that it's not working in fact.
I'll work on something soon to support.

If you want to work on a PR for this, I assume you'll need to make one modification for the [angle stored as the yaw](https://github.com/dulaccc/DPMeterView/blob/master/DPMeterView/DPMeterView.m#L471).

**Comment by AlexanderNorway** [comment]
Any update on this?

**Comment by dulaccc** [comment]
It took me forever to take some time, but I finally manage to find some time.
It's in the b1d2e3d59b36a0ddcd6d916880f76d840e41209d commit.
