### ISSUE TITLE
New pod version with latest code

### ISSUE THREAD

**Issue by levo4ka** [dulaccc/DPMeterView#8]
Hi Pierre, I'm not sure, that it should be marked as issue. It more like question. Do you have a plan to update pod version with latest updates for https://github.com/dulaccc/DPMeterView/commit/6b86e4bf20148b8a6dd09ab4b419ecfb4942609b commit?

In this commit repo has new great feature and will be awesome to have it by default via download by pod file.

**Comment by dulaccc** [comment]
I've just bump the version [1.1.0](https://github.com/dulaccc/DPMeterView/commit/2edba927ade2886460a1dd186431e6c3c171169c).

Cheers
